### ISSUE TITLE
ask for help

### ISSUE THREAD

**Issue by jungerschwarz** [orchidas/Speech-Denoising#1]
I'm sorry to bother you,but could tell me,that,how can I run this program?
where can i found file named 'Results\Rnew all noise estimated order\white\J1_J2_plots_white.mat'?
Is there any script to produce this file?
It's so nice of you if you can help,Thanks!!

**Comment by orchidas** [comment]
I updated KF_speech.m so that it produces the .mat file. However i wrote some clunky code back in the day so the paths are hardcoded and unless you have the noisly files in the same path, it won't work. Of course you could change the path to your path manually by digging into KF_speech.m

If you are just looking for a function to test on individual noisy files, let me know. KF_speech tests for a bunch of parameters and generates too many plots that I needed for my thesis, but probably not too useful for others using it.

**Comment by ghost** [comment]
I would be interested for the function to test on individual noisy files, if you can please provide it. Very nice job on the algorithm and research! :)

**Comment by orchidas** [comment]
Finally added functions to test individual files.
cmi_tuned_kalman_speech.m - Uses the exact algorithm given in the referenced IEEE paper.
kalman_speech_varQ - Let's the user choose which value of process noise to work with
